# Generated by Django 4.2.20 on 2025-05-14 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_societario', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Polisportiva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('città', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=200, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('superficie', models.CharField(choices=[('terra', 'terra'), ('sintetico', 'sintetico'), ('erba', 'erba'), ('cemento', 'cemento')], max_length=20)),
                ('tipo', models.CharField(choices=[('calcio a 5', 'calcio a 5'), ('tennis', 'tennis'), ('padel', 'padel')], max_length=20)),
                ('polisportiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campi', to='accounts.polisportiva')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('durata', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stato', models.CharField(choices=[('in attesa', 'In attesa'), ('accettata', 'accettata'), ('annullata', 'Annullata')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='accounts.campo')),
            ],
            options={
                'unique_together': {('campo', 'data', 'ora_inizio', 'ora_fine')},
            },
        ),
    ]
