# Generated by Django 4.2.20 on 2025-05-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_polisportiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='nome',
            field=models.CharField(default='campo 1', max_length=100),
            preserve_default=False,
        ),
    ]
