# Generated by Django 4.2.20 on 2025-05-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_campo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('in attesa', 'in attesa'), ('accettata', 'accettata'), ('annullata', 'annullata')], default='accettata', max_length=20),
        ),
    ]
