# Generated by Django 4.2.20 on 2025-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_prenotazione_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='pagato',
            field=models.BooleanField(default=False),
        ),
    ]
