# Generated by Django 4.2.20 on 2025-06-12 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_prenotazione_pagato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corsi_gestiti', to=settings.AUTH_USER_MODEL)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corsi', to='accounts.campo')),
            ],
        ),
    ]
